trainingcenter.dashboard:
  path: '/trainingcenter/dashboard'
  defaults:
    _title: 'Dashboard'
    _controller: '\Drupal\trainingcenter\Controller\TrainingcenterController::build'
  requirements:
    _permission: 'access content'

trainingcenter.upload_file:
  path: '/upload/file'
  defaults:
    _form:  '\Drupal\trainingcenter\Form\SimpleForm2'
    _title: 'Upload - file'
  requirements:
    _permission: 'access content'
