trainingcenter.dashboard:
  path: '/trainingcenter/dashboard'
  defaults:
    _title: 'Dashboard'
    _controller: '\Drupal\trainingcenter\Controller\TrainingcenterController::build'
  requirements:
    _permission: 'access content'

trainingcenter.settings_form:
  path: '/admin/config/system/trainingcenter'
  defaults:
    _title: 'Trainingcenter settings'
    _form: 'Drupal\trainingcenter\Form\SettingsForm'
  requirements:
    _permission: 'administer trainingcenter configuration'
