trainingcenter.content:
  path: '/trainingcenter'
  defaults:
	_controller: 'Drupal\Trainingcenter\Controller\TrainingcenterController::content'
	_title: 'Hello world'
  requirements:
	_permission: 'access content'