# Schema for the configuration files of the Trainingcenter module.
trainingcenter.settings:
  type: config_object
  label: 'Trainingcenter settings'
  mapping:
    example:
      type: string
      label: 'Example'
